all: multi-hop-locks.png multi-hop-locks-penalty.png

multi-hop-locks.png: multi-hop-locks.txt
	plantuml -pipe <$< >$@

multi-hop-locks-penalty.png: multi-hop-locks-penalty.txt
	plantuml -pipe <$< >$@
